export const knowledge = [
  {
    id: "mortgage-broker",
    title: "Mortgage broker or adviser",
    jurisdiction: "ROI/NI",
    summary: "A broker or adviser can help compare mortgage options and organise an application.",
    keyPoints: ["You can speak to one before finding a house.", "Many are paid by lenders, but some charge fees.", "Ask how they are paid before proceeding."],
    caution: "A broker is not a final lender decision.",
    officialUrl: "https://www.ccpc.ie/consumers/money/mortgages/",
    sourceLabel: "CCPC mortgage guidance",
    lastReviewed: "2026-07-21",
    relatedRoute: "/buying-guide",
    keywords: ["broker", "adviser", "mortgage", "contact first", "who should i contact"],
  },
  {
    id: "solicitor-conveyancing",
    title: "Solicitor or conveyancer",
    jurisdiction: "ROI/NI",
    summary: "The solicitor or conveyancer handles legal checks and the transfer of ownership.",
    keyPoints: ["They check title, contracts, planning and searches.", "They deal with the seller's legal representative.", "They help you understand when the contract becomes binding."],
    caution: "Ask for a written quote and what is included.",
    officialUrl: "https://www.citizensinformation.ie/en/housing/owning-a-home/buying-a-home/steps-involved-in-buying-a-home/",
    sourceLabel: "Citizens Information",
    lastReviewed: "2026-07-21",
    relatedRoute: "/buying-guide",
    keywords: ["solicitor", "conveyancing", "legal", "contract", "title", "searches"],
  },
  {
    id: "survey-valuation",
    title: "Survey versus valuation",
    jurisdiction: "ROI/NI",
    summary: "A lender valuation is mainly for the lender. An independent survey is for the buyer.",
    keyPoints: ["A valuation does not replace a survey.", "A survey can flag condition issues to investigate.", "A surveyor cannot make legal or lending decisions."],
    caution: "Do not treat listing text or photos as proof of condition.",
    officialUrl: "https://www.scsi.ie/",
    sourceLabel: "SCSI",
    lastReviewed: "2026-07-21",
    relatedRoute: "/check-listing",
    keywords: ["survey", "valuation", "surveyor", "condition", "older", "damp", "roof"],
  },
  {
    id: "booking-deposit",
    title: "Booking deposit",
    jurisdiction: "ROI",
    summary: "A booking deposit is often paid after an offer is accepted in the Republic of Ireland.",
    keyPoints: ["It normally forms part of the overall buyer deposit.", "It is usually refundable before contracts are signed.", "The amount varies."],
    caution: "Confirm refund terms before paying.",
    officialUrl: "https://www.citizensinformation.ie/en/housing/owning-a-home/buying-a-home/steps-involved-in-buying-a-home/",
    sourceLabel: "Citizens Information",
    lastReviewed: "2026-07-21",
    relatedRoute: "/buying-guide",
    keywords: ["booking deposit", "deposit", "refundable", "sale agreed", "offer accepted"],
  },
  {
    id: "cash-beyond-deposit",
    title: "Costs beyond the deposit",
    jurisdiction: "ROI/NI",
    summary: "Buying usually needs separate money for legal, tax, survey, valuation, insurance, moving and a buffer.",
    keyPoints: ["Do not use all savings for the deposit.", "Exact costs vary.", "Keep emergency savings where possible."],
    caution: "Illustrative estimates are not quotes.",
    officialUrl: "https://www.ccpc.ie/consumers/money/mortgages/buying-a-home/",
    sourceLabel: "CCPC buying a home",
    lastReviewed: "2026-07-21",
    relatedRoute: "/savings-plan",
    keywords: ["cash", "costs", "hidden costs", "beyond deposit", "stamp duty", "sdlt", "moving"],
  },
  {
    id: "co-ownership-ni-detail",
    title: "Co-Ownership",
    jurisdiction: "NI",
    summary: "Co-Ownership is a Northern Ireland shared ownership route.",
    keyPoints: ["You buy a share and pay rent on the rest.", "Rules and property limits must be checked with the official provider.", "It is not the same as a standard purchase."],
    caution: "HomePath cannot decide eligibility.",
    officialUrl: "https://www.co-ownership.org/",
    sourceLabel: "Co-Ownership",
    lastReviewed: "2026-07-21",
    relatedRoute: "/advice-centre",
    keywords: ["co-ownership", "northern ireland", "ni", "shared ownership"],
  },
  {
    id: "older-homes",
    title: "Older homes",
    jurisdiction: "ROI/NI",
    summary: "An older home is not automatically a bad purchase, but it may need more investigation.",
    keyPoints: ["Ask about roof, damp, wiring, plumbing, heating, windows, drainage and extensions.", "Use a surveyor for condition.", "Use a solicitor or conveyancer for legal and planning documents."],
    caution: "Do not diagnose defects from a listing alone.",
    officialUrl: "https://www.scsi.ie/",
    sourceLabel: "SCSI",
    lastReviewed: "2026-07-21",
    relatedRoute: "/check-listing",
    keywords: ["older", "renovation", "damp", "rot", "wiring", "plumbing", "roof", "structural"],
  },
  {
    id: "affordable-purchase-roi",
    title: "Affordable Purchase",
    jurisdiction: "ROI",
    summary: "Affordable Purchase schemes may provide new homes below open-market prices through local authorities or approved providers.",
    keyPoints: ["Availability is local and property-specific.", "Income, mortgage capacity and household criteria can matter.", "The local authority or provider makes the decision."],
    caution: "Do not assume a user is eligible because their target price is difficult.",
    officialUrl: "https://affordablehomes.ie/",
    sourceLabel: "Affordable Homes",
    lastReviewed: "2026-07-26",
    relatedRoute: "/advice-centre",
    keywords: ["affordable purchase", "affordable home", "local authority", "price gap", "support route"],
  },
  {
    id: "first-home-scheme-roi",
    title: "First Home Scheme",
    jurisdiction: "ROI",
    summary: "The First Home Scheme is a shared-equity route that could help bridge a gap on an eligible home.",
    keyPoints: ["It is not a cash grant.", "Eligible property types and price ceilings must be checked.", "Future sale or buy-out choices can be affected."],
    caution: "HomePath cannot decide whether a home or buyer fits the scheme.",
    officialUrl: "https://www.firsthomescheme.ie/",
    sourceLabel: "First Home Scheme",
    lastReviewed: "2026-07-26",
    relatedRoute: "/advice-centre",
    keywords: ["first home scheme", "shared equity", "price ceiling", "new build", "gap"],
  },
  {
    id: "social-housing-roi",
    title: "Social housing support",
    jurisdiction: "ROI",
    summary: "Social housing support may be relevant where a household cannot meet housing need from its own resources.",
    keyPoints: ["Applications usually go through the local authority.", "Income, household need and local rules matter.", "Waiting times and available homes vary."],
    caution: "Only the local authority can assess an application.",
    officialUrl: "https://www.citizensinformation.ie/en/housing/local-authority-and-social-housing/applying-for-local-authority-housing/",
    sourceLabel: "Citizens Information",
    lastReviewed: "2026-07-26",
    relatedRoute: "/advice-centre",
    keywords: ["social housing", "housing list", "hap", "housing need", "local authority housing", "insecure"],
  },
  {
    id: "cost-rental-roi",
    title: "Cost Rental",
    jurisdiction: "ROI",
    summary: "Cost Rental may offer longer-term renting where rents are linked to the cost of providing the home.",
    keyPoints: ["It is a renting route, not ownership.", "Availability is limited and schemes are location-specific.", "Income and application rules must be checked."],
    caution: "HomePath cannot say whether a household can access a cost rental home.",
    officialUrl: "https://www.gov.ie/en/service/81d5c-cost-rental-housing/",
    sourceLabel: "gov.ie Cost Rental",
    lastReviewed: "2026-07-26",
    relatedRoute: "/advice-centre",
    keywords: ["cost rental", "renting", "rent support", "not ready to buy"],
  },
  {
    id: "local-authority-home-loan-roi",
    title: "Local Authority Home Loan",
    jurisdiction: "ROI",
    summary: "A Local Authority Home Loan may be worth checking where standard lending is not enough or not available.",
    keyPoints: ["It is still a mortgage.", "Criteria and loan limits must be checked officially.", "The local authority assesses the application."],
    caution: "Do not treat a HomePath estimate as loan approval.",
    officialUrl: "https://localauthorityhomeloan.ie/",
    sourceLabel: "Local Authority Home Loan",
    lastReviewed: "2026-07-26",
    relatedRoute: "/advice-centre",
    keywords: ["local authority home loan", "mortgage refused", "loan", "council mortgage"],
  },
  {
    id: "co-ownership-ni",
    title: "Co-Ownership",
    jurisdiction: "NI",
    summary: "Co-Ownership is a Northern Ireland shared ownership route where a buyer purchases a share and pays rent on the rest.",
    keyPoints: ["It can reduce the mortgage needed at the start.", "Property and affordability rules apply.", "Rent and mortgage both need to be affordable."],
    caution: "Only Co-Ownership can confirm if a route applies.",
    officialUrl: "https://www.co-ownership.org/",
    sourceLabel: "Co-Ownership",
    lastReviewed: "2026-07-26",
    relatedRoute: "/advice-centre",
    keywords: ["co-ownership", "co ownership", "shared ownership", "northern ireland", "ni"],
  },
  {
    id: "social-housing-ni",
    title: "NI social housing",
    jurisdiction: "NI",
    summary: "The Northern Ireland Housing Executive manages applications for social housing and housing need assessment.",
    keyPoints: ["The official assessment uses housing need and points.", "Housing associations may provide homes through the system.", "Local availability matters."],
    caution: "HomePath cannot estimate points or confirm priority.",
    officialUrl: "https://www.nihe.gov.uk/Housing-Help/Apply-for-a-home",
    sourceLabel: "NI Housing Executive",
    lastReviewed: "2026-07-26",
    relatedRoute: "/advice-centre",
    keywords: ["housing executive", "social housing ni", "housing association", "points", "homeless", "urgent"],
  },
  {
    id: "vacant-home-renovation",
    title: "Vacant-home or renovation route",
    jurisdiction: "ROI/NI",
    summary: "A cheaper home needing work can look attractive, but the repair budget and survey risk matter.",
    keyPoints: ["A survey is important before relying on renovation as a route.", "Grants may have rules, timing issues and cashflow gaps.", "Keep a repair buffer separate from deposit money."],
    caution: "Do not assume a grant or low asking price makes the home affordable.",
    officialUrl: "https://www.gov.ie/en/service/f8f1b-vacant-property-refurbishment-grant/",
    sourceLabel: "Vacant Property Refurbishment Grant",
    lastReviewed: "2026-07-26",
    relatedRoute: "/check-listing",
    keywords: ["vacant", "derelict", "renovation", "refurbishment", "grant", "needs work"],
  },
];

export function retrieveKnowledge(question = "", route = "") {
  const text = `${question} ${route}`.toLowerCase();
  const scored = knowledge.map(item => ({
    item,
    score: item.keywords.reduce((sum, key) => sum + (text.includes(key) ? 1 : 0), 0),
  }));
  return scored
    .filter(x => x.score > 0)
    .sort((a,b) => b.score - a.score)
    .slice(0, 4)
    .map(x => x.item);
}

export function fallbackKnowledge() {
  return knowledge.slice(0, 4);
}
