import React, { useState } from "react";
import { Disclaimer, PageHead } from "../components/Layout";
import { getCompletedModules, toggleModuleComplete } from "../lib/storage";

const modules = [
  {id:"cash-needed",cat:"Buying basics",title:"How much cash do I actually need?",source:"CCPC",reviewed:"July 2026",tool:"/savings-plan",idea:"The deposit is only one part of the cash target. You also need buying costs and a buffer.",scenario:"You have €25,000 saved and a 10% deposit target, but legal fees, stamp duty, survey and moving costs still need a separate plan.",q:"Which is the safest way to think about the deposit?",a:"The booking deposit, full buyer deposit and buying costs are different parts of the budget."},
  {id:"broker",cat:"Mortgages and money",title:"What does a mortgage broker do?",source:"CCPC",reviewed:"July 2026",tool:"/check-position",idea:"A broker can compare lenders and help organise an application, but you should ask how they are paid.",scenario:"You have not found a house yet. You can still speak to a broker to understand your rough position.",q:"Does speaking to a broker commit you to a mortgage?",a:"No. It is an information-gathering step."},
  {id:"solicitor-checks",cat:"Legal and conveyancing",title:"What does a solicitor check?",source:"Citizens Information",reviewed:"July 2026",tool:"/buying-guide",idea:"Your solicitor checks the legal side of the purchase, not the physical condition of the house.",scenario:"The house looks fine at viewing, but the solicitor still checks title, planning, boundaries, contracts and mortgage legal documents.",q:"Who checks legal title?",a:"Your solicitor or conveyancer."},
  {id:"conveyancing",cat:"Legal and conveyancing",title:"What is conveyancing?",source:"Citizens Information",reviewed:"July 2026",tool:"/glossary",idea:"Conveyancing means the legal work that transfers ownership from the seller to the buyer.",scenario:"You go sale agreed. Your solicitor requests contracts and begins checking title, planning, boundaries, searches and mortgage legal documents.",q:"Does conveyancing mean a survey?",a:"No. Conveyancing is legal work. A survey checks condition."},
  {id:"booking-deposit",cat:"Buying basics",title:"Booking deposit versus full deposit",source:"Citizens Information",reviewed:"July 2026",tool:"/buying-guide",idea:"A booking deposit is not the same thing as the full buyer deposit.",scenario:"A seller accepts your offer and the estate agent asks for a booking deposit. It normally forms part of the overall buyer deposit and is usually refundable before contracts.",q:"Is every booking deposit exactly €10,000?",a:"No. It varies and should be confirmed before paying."},
  {id:"survey-valuation",cat:"Viewing and older homes",title:"Survey versus lender valuation",source:"RICS / SCSI guidance",reviewed:"July 2026",tool:"/check-listing",idea:"A valuation is mainly for the lender. A survey is for you.",scenario:"The lender values the property and is satisfied. You still arrange a survey because the valuation may not inspect defects in detail.",q:"Which check is for the buyer’s protection?",a:"The independent survey."},
  {id:"contracts",cat:"Legal and conveyancing",title:"Contracts and when you are legally committed",source:"Citizens Information / NI Direct",reviewed:"July 2026",tool:"/buying-guide",idea:"The risky moment is when contracts are signed or exchanged, not when an offer is first accepted.",scenario:"Your offer is accepted, but your solicitor has not finished checks. You wait for legal advice before signing.",q:"Is an accepted offer the same as owning the home?",a:"No. Legal commitment normally comes later."},
  {id:"delays",cat:"Legal and conveyancing",title:"Common delays in buying a home",source:"HomePath guide",reviewed:"July 2026",tool:"/buying-guide",idea:"Delays often come from missing documents, lender conditions, survey issues, title questions or slow replies.",scenario:"The bank asks for one more statement and the solicitor is waiting for planning documents. Both can slow the process.",q:"What helps reduce delays?",a:"Have documents ready and ask each professional what they need next."},
  {id:"viewing-questions",cat:"Viewing and older homes",title:"Questions to ask at a viewing",source:"HomePath listing checker",reviewed:"July 2026",tool:"/check-listing",idea:"A viewing is not just about whether you like the house. It is your chance to spot what needs checking.",scenario:"You ask about roof work, heating, wiring, damp, planning, management fees and what is included in the sale.",q:"Should you rely on listing photos alone?",a:"No. Use a checklist and follow up with professionals."},
  {id:"older-house",cat:"Viewing and older homes",title:"Should I be afraid of an older house?",source:"HomePath guide",reviewed:"July 2026",tool:"/check-listing",idea:"An older house may need more investigation, but age alone does not make a home a bad purchase.",scenario:"A survey mentions rising damp. You ask the surveyor about the cause and likely extent rather than assuming one specific defect.",q:"What should you do with visible damp?",a:"Ask a suitable professional to investigate the cause, extent and urgency."},
  {id:"renovation-costs",cat:"Viewing and older homes",title:"Renovation costs: minor, moderate and major",source:"HomePath guide",reviewed:"July 2026",tool:"/check-listing",idea:"Renovation costs are best treated as broad categories until a professional has checked the property.",scenario:"New paint is not the same as rewiring, roof repairs or structural work. You keep a contingency instead of assuming one exact price.",q:"Should HomePath diagnose repair costs from a listing?",a:"No. It can flag categories to investigate."},
  {id:"supports",cat:"Public supports",title:"Public supports explained",source:"Official scheme pages",reviewed:"July 2026",tool:"/advice-centre",idea:"Supports may be worth checking, but HomePath should not make eligibility decisions.",scenario:"You read about Help to Buy, First Home Scheme or Co-Ownership, then check the official provider’s current rules.",q:"Should you rely on old scheme limits from social media?",a:"No. Check the official source."},
];

const categories = ["Buying basics","Mortgages and money","Legal and conveyancing","Public supports","Viewing and older homes"];
const olderIssues = ["Roofs","Rising damp and other forms of damp","Dry rot and wet rot","Windows","Heating systems","Wiring","Plumbing and drainage","Subsidence and structural movement","Extensions and alterations","BER and energy upgrades","Surveys versus lender valuations"];

export default function LearnPage({ navigate }) {
  const [completed,setCompleted]=useState(getCompletedModules());
  const [open,setOpen]=useState(modules[0].id);
  const done = id => { const next=toggleModuleComplete(id); setCompleted(next); };
  return <div className="page learn-page"><PageHead eyebrow="Buying basics modules" title="Small lessons that make buying, borrowing and maintaining a home easier to understand.">Pick one short module. Each one is designed to take a few minutes, not an evening.</PageHead>
    <section className="learn-progress"><div><strong>{completed.length}</strong><span>modules completed</span></div><div className="progress-track"><span style={{width:`${completed.length/modules.length*100}%`}} /></div><p>Recommended next module: {modules.find(m=>!completed.includes(m.id))?.title || "You have completed the pilot set."}</p></section>
    <div className="category-row">{categories.map(cat=><span key={cat}>{cat}<small>{modules.filter(m=>m.cat===cat && completed.includes(m.id)).length}/{Math.max(1,modules.filter(m=>m.cat===cat).length)}</small></span>)}</div>
    <section className="module-list">{modules.map(m=><article className={`module-card ${open===m.id?"open":""}`} key={m.id}><button onClick={()=>setOpen(open===m.id?"":m.id)}><span>{completed.includes(m.id)?"✓":"○"}</span><strong>{m.title}</strong><small>{m.cat}</small></button>{open===m.id&&<div><p className="eyebrow">One clear idea</p><p>{m.idea}</p><div className="scenario-card"><h3>Scenario</h3><p>{m.scenario}</p></div><h3>Quick check</h3><p>{m.q}</p><p className="answer">{m.a}</p><p><small>Last reviewed: {m.reviewed} · Source: {m.source}</small></p><button className="primary" onClick={()=>done(m.id)}>{completed.includes(m.id)?"Mark incomplete":"Mark complete"} <span>✓</span></button><button className="guide-inline-button" onClick={()=>navigate(m.tool)}>Open related tool</button></div>}</article>)}</section>
    <section className="plain-card"><h2>Older homes: what to investigate</h2><p>An older home may need more investigation, but age alone is not a reason to dismiss it. Costs vary greatly by property, access, location, extent and specification.</p><div className="older-grid">{olderIssues.map(x=><article key={x}><h3>{x}</h3><p>Look for visible signs, ask direct viewing questions, and have the right professional check it. Category: moderate investigation or potentially significant depending on extent.</p></article>)}</div></section>
    <Disclaimer>Lessons are general guidance. They do not replace advice from a broker, lender, solicitor, surveyor, tax authority or official scheme provider.</Disclaimer>
  </div>
}
